### ISSUE TITLE
IfcNumericMeasure values read looses decimal part...

### ISSUE THREAD

**Issue by flocou** [cstb/ifc-sdk#10]
When trying to read an IfcNumericMeasure, only the integer part is kept, while IfcNumericMeasure is defined as a Real number...
Error seems to be @ line 189 of file IfcPropertySingleValue.cpp, where we try to parse a double value as an int....

**Comment by mathieu** [comment]
[link to line](https://github.com/cstb/ifc-sdk/blob/ef8870a20e1f73c0e1cc8ed20aa0d188f7c990cf/src/ifc2x3/IfcPropertySingleValue.cpp#L189)

NUMBER is a Real value ?

**Comment by flocou** [comment]
Yes:
`typedef Real Number;` in SimpleTypes.h

**Comment by marache** [comment]
Ok that was closed by merging #11
